### ISSUE TITLE
MySQL OperationalError: (1093, "You can't specify target table 'wagtailimages_rendition' for update in FROM clause")

### ISSUE THREAD

**Issue by AEzzatA** [torchbox/wagtail#1032]
This is just the fresh install migrations of wagtail==0.8.5 Django==1.7.5 and MySQL  5.6.19-0ubuntu0.14.04.1 and 

Keep in mind this error doesn't happen with neither PostgreSQL nor SQLite.
what seems to be wrong here? and how to solve it?

  Applying wagtailimages.0004_make_focal_point_key_not_nullable...Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 105, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/wagtail/wagtailimages/migrations/0004_make_focal_point_key_not_nullable.py", line 12, in remove_duplicate_renditions
    """)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 103, in execute
    cursor.execute(sql, params)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/is7yx/.virtualenvs/lux/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1093, "You can't specify target table 'wagtailimages_rendition' for update in FROM clause")

**Comment by m-sanders** [comment]
This is a known issue: https://github.com/torchbox/wagtail/issues/541

MySQL is currently not support :(

**Comment by gasman** [comment]
This specific bug has been fixed in #827. As @m-sanders says, there's still no official MySQL support, but git master (and the forthcoming 0.9) have no known blocking MySQL bugs.

**Comment by AEzzatA** [comment]
Thanks @m-sanders  and @gasman. planning to PostgreSQL is a good idea I believe
