### ISSUE TITLE
Inline editable object doesn't save tags

### ISSUE THREAD

**Issue by mrbox** [torchbox/wagtail#1221]
I think that's related to https://github.com/torchbox/wagtail/issues/197 - when I have structure that is one level deeper, my tags aren't saved:

```
class GalleryItemTag(TaggedItemBase):
    content_object = ParentalKey('core.GalleryPageItem', related_name='tagged_items')

class GalleryPageItem(Orderable, GalleryItem):
    page = ParentalKey('core.GalleryPage', related_name='gallery_items')
    tags = ClusterTaggableManager(through=GalleryItemTag, blank=True)

    panels = GalleryItem.panels + [
        FieldPanel('tags'),
    ]

class GalleryPage(Page):
    pass

GalleryPage.content_panels = [
    FieldPanel('title', classname="full title"),
    InlinePanel(GalleryPage, 'gallery_items', label="Gallery items"),
]

GalleryPage.promote_panels = Page.promote_panels
```

I see `tags` input on the GalleryPage edit screen, I have autocomplete there, but can't save them.

**Comment by stefaniadem** [comment]
I have the same issue, any fix for this?

**Comment by stefangeorg** [comment]
solved it by doing this instead

```python
class NewsItem(Orderable, models.Model):
    page = ParentalKey(NewsPage, related_name='news_items', on_delete=models.PROTECT)
    title = models.CharField(max_length=255)
    link = models.URLField(blank=True)
    date_to_show = models.DateField(default=datetime.datetime.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    news_tags = TaggableManager(related_name='news_tags')

    panels = [
        FieldPanel('title'),
        FieldPanel('link'),
        FieldPanel('date_to_show'),
        ImageChooserPanel('image'),
        FieldPanel('news_tags')
    ]
```

So instead of following the docs and using a through model (as these are inlines and not regular Pages), just drop the extra through in the TaggableManager and no need for the  GalleryItemTag or in my case the NewsItemTag model.

**Comment by gasman** [comment]
It's _possible_ that the new version 3.1 of the django-modelcluster library released yesterday fixes this, as it includes a bugfix relating to saving of tag fields - would be good if someone could check this.

Also, looking at the above code, I think `GalleryPageItem` needs to inherit from `modelcluster.models.ClusterableModel`.

**Comment by thenewguy** [comment]
@gasman Is there a minimal code snippet available anywhere that demonstrates how to use tags (utilizing the default taggit TaggedItem) on a model included by an InlinePanel?  I've searched but not been able to find anything.

Adjusted from the original example like:

```
from taggit.models import TaggedItem

class GalleryPage(Page):
    pass

class GalleryPageItem(models.Model):
    page = ParentalKey(GalleryPage, related_name='gallery_items')
    tags = ClusterTaggableManager(through=TaggedItem, blank=True)

GalleryPage.content_panels = [
    InlinePanel(GalleryPage, 'gallery_items', label="Gallery items"),
]
```

I've tried with and without using `ClusterableModel` and I end up with:

```
Traceback (most recent call last):
  File "/.../django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/.../django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/.../django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/.../wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/.../wagtail/admin/auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/.../django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/.../wagtail/admin/views/pages/edit.py", line 131, in dispatch
    return super().dispatch(request)
  File "/.../django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/.../wagtail/admin/views/pages/edit.py", line 218, in post
    return self.form_valid(self.form)
  File "/.../wagtail/admin/views/pages/edit.py", line 238, in form_valid
    return self.publish_action()
  File "/.../wagtail/admin/views/pages/edit.py", line 270, in publish_action
    self.page = self.form.save(commit=False)
  File "/.../modelcluster/forms.py", line 374, in save
    formset.save(commit=commit)
  File "/.../modelcluster/forms.py", line 93, in save
    saved_instances = super(BaseChildFormSet, self).save(commit=False)
  File "/.../django/forms/models.py", line 673, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/.../django/forms/models.py", line 811, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/.../django/forms/models.py", line 650, in save_new
    return form.save(commit=commit)
  File "/.../modelcluster/forms.py", line 367, in save
    self.save_m2m()
  File "/.../django/forms/models.py", line 443, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/.../taggit/managers.py", line 543, in save_form_data
    getattr(instance, self.name).set(*value)
  File "/.../taggit/utils.py", line 124, in inner
    return func(self, *args, **kwargs)
  File "/.../modelcluster/contrib/taggit.py", line 78, in set
    return super(_ClusterTaggableManager, self).set(*tags, clear=True)
  File "/.../taggit/utils.py", line 124, in inner
    return func(self, *args, **kwargs)
  File "/.../taggit/managers.py", line 271, in set
    self.clear()
  File "/.../taggit/utils.py", line 124, in inner
    return func(self, *args, **kwargs)
  File "/.../modelcluster/contrib/taggit.py", line 82, in clear
    self.get_tagged_item_manager().clear()
  File "/.../taggit/utils.py", line 124, in inner
    return func(self, *args, **kwargs)
  File "/.../modelcluster/contrib/taggit.py", line 23, in get_tagged_item_manager
    rel_name = self.through._meta.get_field('content_object').remote_field.get_accessor_name()

Exception Type: AttributeError at /dashboard/pages/3/edit/
Exception Value: 'NoneType' object has no attribute 'get_accessor_name'
```

**Comment by gsakkis** [comment]
Bump - not sure if it's the same (8 year old!) issue but I can't get [tagging snippets](https://docs.wagtail.org/en/stable/topics/snippets.html#tagging-snippets) to work from the admin interface. The field panel shows up find, the tags are submitted with the request but no SQL insert statement(s) related to the tag tables is submitted as far as I can tell from the debug toolbar.

**Comment by laymonage** [comment]
@gsakkis did you make sure that the snippet extends `ClusterableModel` and that you use `ClusterTaggableManager` instead of `TaggableManager`?

**Comment by gasman** [comment]
@laymonage Looks like this is a documentation issue - https://docs.wagtail.org/en/stable/topics/snippets.html#tagging-snippets specifically says to use `TaggableManager` rather than `ClusterTaggableManager`, presumably because it was written before `DraftStateMixin` was introduced.

**Comment by laymonage** [comment]
Yep, I think you're right @gasman

We do mention it in the "Saving revisions of snippets":

https://docs.wagtail.org/en/stable/topics/snippets.html#saving-revisions-of-snippets

> If your snippet model defines relations using Django’s [ManyToManyField](https://docs.djangoproject.com/en/stable/ref/models/fields/#django.db.models.ManyToManyField), you need to change the model class to inherit from modelcluster.models.ClusterableModel instead of django.models.Model and replace the ManyToManyField with ParentalManyToManyField. Inline models should continue to use ParentalKey instead of ForeignKey. This is necessary in order to allow the relations to be stored in the revisions. See the [Categories](https://docs.wagtail.org/en/stable/getting_started/tutorial.html#tutorial-categories) section of the tutorial for more details. For example:

But I think the Tagging snippets documentation is outdated and should mention that if `RevisionMixin` enabled (which is also the case if `DraftStateMixin` is enabled), then `ClusterTaggableManager` should be used.

**Comment by gsakkis** [comment]
Thanks @gasman and @laymonage, i confirmed that replacing `TaggableManager` with `ClusterTaggableManager` fixes it!

**Comment by gsakkis** [comment]
Sorry to abuse this ticket but perhaps I rushed to celebrate - although the tags are saved correctly on every draft revision, the `through` model of the `ClusterTaggableManager` (`AdvertTag` in the docs) is not updated, it preserves the initial tags at instance creation (if any). 

In other words this is correct:
```py
list(Advert.objects.get(id=1).latest_revision.as_object().tagged_items.all())
```
This is not:
```py
list(AdvertTag.objects.filter(content_object_id=1))
```

Is this expected and I should just always use the latest_revision or it's a (different) bug?

**Comment by BertrandBordage** [comment]
On Wagtail 5.2.2, what kind of works is making the inline model inherit from `ClusterableModel` and using `TaggableManager` (not `ClusterTaggableManager`) with a `through` argument to a custom model inheriting from `TaggedItemBase`.

That being said, changes to the inline tags **are not visible in the diff** when you compare 2 versions.
