### ISSUE TITLE
Can't use Page model as proxy model

### ISSUE THREAD

**Issue by chhantyal** [torchbox/wagtail#1265]
It gives following error while running management command:

````
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x110867a28>
Traceback (most recent call last):
  File "/Users/user/projects/projectname/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 223, in wrapper
    fn(*args, **kwargs)
  File "/Users/user/projects/projectname/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    self.validate(display_num_errors=True)
  File "/Users/user/projects/projectname/env/lib/python2.7/site-packages/django/core/management/base.py", line 465, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/Users/user/projects/projectname/env/lib/python2.7/site-packages/django/core/management/base.py", line 478, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/user/projects/projectname/env/lib/python2.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/user/projects/projectname/env/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/Users/user/projects/projectname/env/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 387, in check
    field_exceptions = [field.name for model in [cls] + list(cls._meta.get_parent_list()) for field in model._meta.parents.values()]
AttributeError: 'NoneType' object has no attribute 'name'
````
My  proxy model:

````
class PageMeta(Page):
    inherited_objects = InheritanceManager()

    class Meta:
        proxy = True
````
Which is inherited by BlogPage etc.

I am using master branch, with Django 1.8

**Comment by kaedroho** [comment]
Fixed by #1266
