### ISSUE TITLE
Getting a KeyError: u'__module__' error when i run python manage.py migrate

### ISSUE THREAD

**Issue by asvarmaa** [torchbox/wagtail#1287]
Can you let me know how to fix this error.

bash % python manage.py migrate
/Library/Python/2.7/site-packages/treebeard/mp_tree.py:102: RemovedInDjango18Warning: `MP_NodeManager.get_query_set` method should be renamed `get_queryset`.
  class MP_NodeManager(models.Manager):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/wagtail/wagtailcore/models.py", line 268, in <module>
    class Page(six.with_metaclass(PageBase, MP_Node, ClusterableModel, index.Indexed)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 71, in __new__
    module = attrs.pop('__module__')
KeyError: u'__module__'

**Comment by gasman** [comment]
Hi @asvarmaa,
Please use the [mailing list](https://groups.google.com/forum/#!forum/wagtail) for support queries.

**Comment by asvarmaa** [comment]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/wagtail/wagtailcore/models.py", line 268, in <module>
    class Page(six.with_metaclass(PageBase, MP_Node, ClusterableModel, index.Indexed)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 71, in __new__
    module = attrs.pop('__module__')
KeyError: u'__module__'

**Comment by asvarmaa** [comment]
Thanks for the update, i have created a new topic in the mailing list
