### ISSUE TITLE
Wagtailforms CSV export crashes on Python 3 when unicodecsv is installed

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1295]
unicodecsv now supports Python 3 so it's possible for a user to have it installed.

When it is installed, Wagtail tries to use it and will crash with the following error:

```
======================================================================
ERROR: test_list_submissions_csv_export (wagtail.wagtailforms.tests.TestFormsSubmissions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karl/projects/wagtail/wagtail/wagtailforms/tests.py", line 356, in test_list_submissions_csv_export
    response = self.client.get(reverse('wagtailforms_list_submissions', args=(self.form_page.id, )), {'date_from': '01/01/2014', 'action': 'CSV'})
  File "/home/karl/projects/wagtail/venv/lib/python3.4/site-packages/django/test/client.py", line 470, in get
    **extra)
  File "/home/karl/projects/wagtail/venv/lib/python3.4/site-packages/django/test/client.py", line 286, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/karl/projects/wagtail/venv/lib/python3.4/site-packages/django/test/client.py", line 358, in generic
    return self.request(**r)
  File "/home/karl/projects/wagtail/venv/lib/python3.4/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/home/karl/projects/wagtail/venv/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/home/karl/projects/wagtail/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/karl/projects/wagtail/venv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 38, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/karl/projects/wagtail/venv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/karl/projects/wagtail/wagtail/wagtailforms/views.py", line 73, in list_submissions
    writer = csv.writer(response, encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by zerolab** [comment]
PR: #1365
