### ISSUE TITLE
Error uploading image

### ISSUE THREAD

**Issue by rmartins90** [torchbox/wagtail#1334]
Traceback (most recent call last):
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 38, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/wagtail/wagtailimages/views/chooser.py", line 124, in chooser_upload
    if form.is_valid():
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/forms/forms.py", line 162, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/forms/forms.py", line 154, in errors
    self.full_clean()
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/forms/forms.py", line 353, in full_clean
    self._clean_fields()
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/forms/forms.py", line 366, in _clean_fields
    value = field.clean(value, initial)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/forms/fields.py", line 606, in clean
    return super(FileField, self).clean(data)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/django/forms/fields.py", line 150, in clean
    value = self.to_python(value)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/wagtail/wagtailimages/fields.py", line 127, in to_python
    self.check_image_file_size(f)
  File "/home/vagrant/webproject/aroucageopark/virtualenv/local/lib/python2.7/site-packages/wagtail/wagtailimages/fields.py", line 120, in check_image_file_size
    filesizeformat(f.size),
TypeError: format requires a mapping

**Comment by rmartins90** [comment]
Sorry, this happens on version 1.0b2

**Comment by kaedroho** [comment]
What version of Django are you using?

**Comment by kaedroho** [comment]
This appears to be caused by a bad format string replacement:
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/fields.py#L34-L38
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/fields.py#L119-L121
(using a tuple instead of a dict)

I noticed a few other places in that file which could potentially cause issues so I think it's worth cleaning that up a bit.

**Comment by kaedroho** [comment]
PR #1368
