### ISSUE TITLE
Creating first site as per documentation page - db migrations fail

### ISSUE THREAD

**Issue by sammcj** [torchbox/wagtail#1402]
Shortcut guide documentation: https://wagtail.io/developers/

Installs fine:
```
samm-mbp ~ % sudo pip install wagtail
Password:
The directory '/Users/samm/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/samm/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/samm/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting wagtail
  Downloading wagtail-0.8.7.tar.gz (1.8MB)
    100% |################################| 1.8MB 70kB/s
Collecting Django<1.8,>=1.6.2 (from wagtail)
  Downloading Django-1.7.8-py2.py3-none-any.whl (7.4MB)
    100% |################################| 7.4MB 27kB/s
Collecting South==1.0.0 (from wagtail)
  Downloading South-1.0.tar.gz (97kB)
    100% |################################| 98kB 100kB/s
Collecting django-compressor>=1.4 (from wagtail)
  Downloading django_compressor-1.5-py2.py3-none-any.whl (129kB)
    100% |################################| 131kB 101kB/s
Collecting django-libsass>=0.2 (from wagtail)
  Downloading django-libsass-0.3.tar.gz
Collecting django-modelcluster>=0.4 (from wagtail)
  Downloading django-modelcluster-0.6.2.tar.gz
Collecting django-taggit==0.12.3 (from wagtail)
  Downloading django_taggit-0.12.3-py2.py3-none-any.whl
Collecting django-treebeard==2.0 (from wagtail)
  Downloading django-treebeard-2.0.tar.gz (92kB)
    100% |################################| 94kB 179kB/s
Collecting Pillow>=2.6.1 (from wagtail)
  Downloading Pillow-2.8.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.8MB)
    100% |################################| 2.8MB 35kB/s
Collecting beautifulsoup4>=4.3.2 (from wagtail)
  Downloading beautifulsoup4-4.3.2.tar.gz (143kB)
    100% |################################| 143kB 97kB/s
Collecting html5lib==0.999 (from wagtail)
  Downloading html5lib-0.999.tar.gz (885kB)
    100% |################################| 888kB 99kB/s
Requirement already satisfied (use --upgrade to upgrade): Unidecode>=0.04.14 in /Library/Python/2.7/site-packages (from wagtail)
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.0 in /Library/Python/2.7/site-packages (from wagtail)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0.0 in /Library/Python/2.7/site-packages (from wagtail)
Collecting unicodecsv>=0.9.4 (from wagtail)
  Downloading unicodecsv-0.13.0.tar.gz
Collecting django-appconf>=0.4 (from django-compressor>=1.4->wagtail)
  Downloading django_appconf-1.0.1-py2.py3-none-any.whl
Collecting libsass>=0.3.0 (from django-libsass>=0.2->wagtail)
  Downloading libsass-0.8.2-cp27-none-macosx_10_10_intel.whl (1.2MB)
    100% |################################| 1.2MB 65kB/s
Collecting pytz>=2015.2 (from django-modelcluster>=0.4->wagtail)
  Downloading pytz-2015.4-py2.py3-none-any.whl (475kB)
    100% |################################| 475kB 118kB/s
Installing collected packages: pytz, libsass, django-appconf, unicodecsv, html5lib, beautifulsoup4, Pillow, django-treebeard, django-taggit, django-modelcluster, django-libsass, django-compressor, South, Django, wagtail
  Found existing installation: pytz 2013.7
    Uninstalling pytz-2013.7:
      Successfully uninstalled pytz-2013.7



  Running setup.py install for unicodecsv
  Running setup.py install for html5lib
  Running setup.py install for beautifulsoup4

  Running setup.py install for django-treebeard

  Running setup.py install for django-modelcluster
  Running setup.py install for django-libsass

  Running setup.py install for South

  Running setup.py install for wagtail
    Installing wagtail script to /usr/local/bin
Successfully installed Django-1.7.8 Pillow-2.8.2 South-1.0 beautifulsoup4-4.3.2 django-appconf-1.0.1 django-compressor-1.5 django-libsass-0.3 django-modelcluster-0.6.2 django-taggit-0.12.3 django-treebeard-2.0 html5lib-0.999 libsass-0.8.2 pytz-2015.4 unicodecsv-0.13.0 wagtail-0.8.7
```

Creates site fine:
```
samm-mbp ~/Desktop % wagtail start mysite
Creating a wagtail project called mysite
Success! mysite is created
```

Migrating the database - not so fine: (I'm assuming it's sqlite by default?)
```
samm-mbp ~/Desktop/mysite % python manage.py migrate
/Library/Python/2.7/site-packages/treebeard/mp_tree.py:102: RemovedInDjango18Warning: `MP_NodeManager.get_query_set` method should be renamed `get_queryset`.
  class MP_NodeManager(models.Manager):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/wagtail/wagtailcore/models.py", line 268, in <module>
    class Page(six.with_metaclass(PageBase, MP_Node, ClusterableModel, index.Indexed)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 71, in __new__
    module = attrs.pop('__module__')
KeyError: u'__module__'
```

- Python 2.7.6
- pip 7.0.3 from /Library/Python/2.7/site-packages (python 2.7)
- OSX 10.10.3

Might be related to https://groups.google.com/forum/#!msg/wagtail/8zBzrIUwyHk/I20kN_dmTj4J

**Comment by kaedroho** [comment]
It looks like you may be using an old version of ``six``. (this line ``return meta("NewBase", bases, {})`` looks like the old implementation of ``with_metaclass``).

Try running ``sudo pip install --upgrade six``

**Comment by sammcj** [comment]
thanks @kaedroho but it's already up to date.

`Requirement already up-to-date: six in /Library/Python/2.7/site-packages`

I'm off for the night now so there's no rush replying :)

**Comment by kaedroho** [comment]
It looks like ``six`` is being loaded from a different place to where pip is installing it (the traceback says six installed at  ``/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py``).

I recommend installing Wagtail into a virtual environment so Python always sees a pip installed version of six.
