### ISSUE TITLE
ImportError: No module named security

### ISSUE THREAD

**Issue by jackwei** [torchbox/wagtail#1458]
Traceback (most recent call last):
  File "D:\Python27\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python27\lib\site-packages\django-1.7.3-py2.7.egg\django\contrib\stat
icfiles\handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "D:\Python27\lib\site-packages\django-1.7.3-py2.7.egg\django\core\handler
s\wsgi.py", line 168, in __call__
    self.load_middleware()
  File "D:\Python27\lib\site-packages\django-1.7.3-py2.7.egg\django\core\handler
s\base.py", line 44, in load_middleware
    mw_class = import_string(middleware_path)
  File "D:\Python27\lib\site-packages\django-1.7.3-py2.7.egg\django\utils\module
_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named security

**Comment by kaedroho** [comment]
If you used the project template, you must use Django 1.8 (it appears you are using 1.7.3 at the moment).

Try running this in the command prompt: ``pip install --upgrade django``

If you have other projects that use Django or Wagtail on your computer, may I suggest you look into installing these packages into a virtual environment? (https://virtualenv.pypa.io/en/latest/)

If you have any more support questions, please post them on our google group: https://groups.google.com/forum/#!forum/wagtail

**Comment by omeryzr** [comment]
remove to row 'django.middleware.security.SecurityMiddleware' in setting.py

**Comment by kaedroho** [comment]
The SecurityMiddleware was added in Django 1.8 so you should consider
updating to that before removing the middleware.
