### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by SalahAdDin** [torchbox/wagtail#1595]
I was working with wagtail 0.8 and i updated to 1.0, i create all migrations and try migrate it but i have this problem:
```bash
django.db.migrations.graph.NodeNotFoundError: Migration wagtailcore.0002_auto_20150811_1940 dependencies reference nonexistent parent node ('wagtailcore', '0001_squashed_0016_change_page_url_path_to_text_field')
```

Can anyone help me?

This is the traceback:
```bash
(CCCT)tulipan@tulipan-Satellite-M645:/media/tulipan/Datos/Proyectos/Trabajo/CCCT/ccct$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/migrations/loader.py", line 299, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/migrations/loader.py", line 282, in _reraise_missing_dependency
    raise exc
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/migrations/loader.py", line 292, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/migrations/graph.py", line 116, in add_dependency
    parent
django.db.migrations.graph.NodeNotFoundError: Migration wagtailcore.0002_auto_20150811_1940 dependencies reference nonexistent parent node ('wagtailcore', '0001_squashed_0016_change_page_url_path_to_text_field')
```

**Comment by kaedroho** [comment]
Please ask support questions on the Google Group: https://groups.google.com/forum/#!forum/wagtail

The migration ``wagtailcore.0002_auto_20150811_1940`` doesn't exist in Wagtail. Try completely uninstalling Wagtail (run "pip uninstall wagtail" a few times) then reinstall it.

**Comment by SalahAdDin** [comment]
Thanks man, i delete this migration and migrate all :D, works, thanks.

**Comment by SalahAdDin** [comment]
But, now i have this problem:
![problema con migrar](https://cloud.githubusercontent.com/assets/5034215/9223567/eb528504-40c0-11e5-8b97-338417fe51d6.png)
Why happen this?

**Comment by gasman** [comment]
Please ask support questions on the Google Group: https://groups.google.com/forum/#!forum/wagtail

**Comment by SalahAdDin** [comment]
Ok, i solve it remaking the migration, i don't know what happen but, remake this migration, wagtailcore.0002_auto_20150811_1940, then migrate it and voila, works.
It seems they need to create an additional migration file, or to do a step, that is, first migrate such wagtail what then do migration for all the additional applications, including wagtailcore, and finally migrate.
Tonight i'll put here a print screen of the process and the result.

**Comment by davecranwell** [comment]
As this ticket is closed and seemed pretty unique to your set up I wouldn't bother uploading a print screen of the process. I'm sure you have better things to be doing with your time :)
