### ISSUE TITLE
Error Editing an Image

### ISSUE THREAD

**Issue by chadsaun** [torchbox/wagtail#1707]
When I click the "Edit this Image" button, I get `ValueError at /cms/images/157/ The file cannot be reopened.`  I'm using Wagtail version 1.1.  I'm also using django-offsite-storage to store all my images in S3.

Here is the full stack trace:

```
Internal Server Error: /cms/images/157/
Traceback (most recent call last):
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/views/images.py", line 136, in edit
    'filesize': image.get_file_size(),
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/templatetags/wagtailimages_tags.py", line 55, in render
    rendition = image.get_rendition(self.filter)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 228, in get_rendition
    generated_image, output_format = filter.run(self, BytesIO())
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 360, in run
    with image.get_willow_image() as willow:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 126, in get_willow_image
    self.file.open('rb')
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/db/models/fields/files.py", line 81, in open
    self.file.open(mode)
  File "/Users/chad/.virtualenvs/website/lib/python2.7/site-packages/django/core/files/base.py", line 141, in open
    raise ValueError("The file cannot be reopened.")
ValueError: The file cannot be reopened.
```

**Comment by chadsaun** [comment]
Here's a screenshot of the error too that may be helpful.

![screen shot 2015-09-17 at 2 14 49 pm](https://cloud.githubusercontent.com/assets/381024/9944918/760677c6-5d47-11e5-807d-a57e6879a53d.png)

**Comment by kaedroho** [comment]
Thanks for reporting. Could you quickly run this check:

In the Django shell
```
>>> from wagtail.wagtailimages.models import Image  # replace this with custom image model if you have one
>>> i = Image.objects.get(id=<put an existing image id here>)
>>> i.is_stored_locally()
# This should return False in your case

```

**Comment by chadsaun** [comment]
Hmm...it actually returned "True"

**Comment by kaedroho** [comment]
Thanks @chadsaun 

There's possibly a bug in ``django-offsite-storage``. Wagtail determines whether a file is stored locally by checking if the ``path`` property returns a value. According to the Django docs (https://docs.djangoproject.com/en/1.8/ref/files/storage/#django.core.files.storage.Storage.path), external file backends must return ``NotImplementedError`` which doesn't look like what's happening here.

We could work around this in Wagtail by implementing this: https://github.com/torchbox/wagtail/pull/1605#discussion_r37023728

**Comment by gasman** [comment]
Hi @chadsaun - I see that there's a new version of django-offsite-storage which adds the missing methods. Can you confirm whether upgrading to django-offsite-storage 0.0.6 or later fixes the issue?

**Comment by chadsaun** [comment]
I've upgraded to django-offsite-storage 0.0.7 and now I do get the error `NotImplementedError at /cms/images/192/`.

On a related note, I've submitted an issue regarding this in Issue #1996

**Comment by gasman** [comment]
Thanks! Will close this ticket in favour of #1996 then, as that one describes the behaviour with (what I assume to be) a correctly-behaving storage backend, and so covers the bug we need to fix on Wagtail's side.
