### ISSUE TITLE
WagtailPageTests Error

### ISSUE THREAD

**Issue by rich-hart** [torchbox/wagtail#2088]
In the ``wagtail.tests.utils.WagtailPageTests`` class the ``assertCanCreate`` method errors when setting the data parameter to an empty dictionary. e.g. ``self.assertCanCreate(HomePage, AboutUs,{})`` throws the following error:

``` pytb
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax-cms/pages/tests/tests.py", line 76, in test_class_setup
    self.assertCanCreate(HomePage, AboutUs,{})
  File "/Users/openstax/workspace/openstax-cms/venv/lib/python3.5/site-packages/wagtail/tests/utils.py", line 106, in assertCanCreate
    self.assertCanCreateAt(parent.specific_class, child_model)
  File "/Users/openstax/workspace/openstax-cms/venv/lib/python3.5/site-packages/wagtail/tests/utils.py", line 79, in assertCanCreateAt
    if not self._testCanCreateAt(parent_model, child_model):
  File "/Users/openstax/workspace/openstax-cms/venv/lib/python3.5/site-packages/wagtail/tests/utils.py", line 71, in _testCanCreateAt
    return child_model in parent_model.allowed_subpage_models()
AttributeError: 'cached_property' object has no attribute 'allowed_subpage_models'
```

**Comment by timheap** [comment]
You need to pass a page instance as the first argument to `assertCanCreate()`, not a page model. The [documentation for assertCanCreate](http://docs.wagtail.io/en/v1.3/advanced_topics/testing.html#wagtail.tests.utils.WagtailPageTests.assertCanCreate) has an example. You might be able to fix this by doing something like:

```python
def test_create_about_us(self):
    homepage = HomePage.objects.first()
    self.assertCanCreate(homepage, AboutUs, {})
```

**Comment by rich-hart** [comment]
I tried something like that but it would then throw a

```pytb
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax-cms/pages/tests/tests.py", line 82, in test_class_setup
    self.assertCanCreate(homepage, AboutUs, {})
  File "/Users/openstax/workspace/openstax-cms/venv/lib/python3.5/site-packages/wagtail/tests/utils.py", line 106, in assertCanCreate
    self.assertCanCreateAt(parent.specific_class, child_model)
AttributeError: 'NoneType' object has no attribute 'specific_class'
```

Perhaps the classes are not constructed properly?

**Comment by rich-hart** [comment]
So the ``HomePage.objects.first()`` returns a None type.  Is there a convenient way to create these object from the testing framework?

**Comment by gasman** [comment]
Hi @rich-hart - please use the [Wagtail Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

**Comment by rich-hart** [comment]
ok
