### ISSUE TITLE
wagtailcore.Page tries to migrate before contenttypes

### ISSUE THREAD

**Issue by bloodywing** [torchbox/wagtail#2433]
I'm getting this error:

`RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.`

**Steps to reproduce:**
create a clean wagtail Project
add this models.py to the home app: https://gist.github.com/bloodywing/175ddf5d0b6d10f9da2cddb2bf2bbd98
run: manage.py migrate

The problem is in the class LinkFields with the ForeignKey to wagtailcore.Page
This is the same LinkFields class which is shown in the wagtail docs.
Tested with: 1.4.2 and master

Workaround:
Comment out PageChooserPanel in the models
run migrations
and put PageChooserPanel back in.

**Comment by ghostwords** [comment]
I ran into this by trying to `manage.py migrate` a Wagtail project from scratch after upgrading to Wagtail 1.4.2.

The issue seems to come from the following change in 56c5a78aa7b02fbbb1c782203f790e0939c7fb05:

```diff
-        # Sadly, there is no way of checking the form class returned from
-        # cls.get_edit_handler().get_form_class(cls), as these calls can hit
-        # the DB in order to fetch content types.
+
+        edit_handler = cls.get_edit_handler()
+        if not issubclass(edit_handler.get_form_class(cls), WagtailAdminPageForm):
+            errors.append(checks.Error(
+                "{cls}.get_edit_handler().get_form_class({cls}) does not extend WagtailAdminPageForm".format(
+                    cls=cls.__name__),
+                hint="Ensure that the EditHandler for {cls} creates a subclass of WagtailAdminPageForm".format(
+                    cls=cls.__name__),
+                obj=cls,
+                id='wagtailcore.E003'))
```

The error that goes away if I revert the above change:

```
Traceback (most recent call last):
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_content_type

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/contrib/contenttypes/models.py", line 67, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_content_type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    self.check()
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/core/management/base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailcore/models.py", line 572, in check
    if not issubclass(edit_handler.get_form_class(cls), WagtailAdminPageForm):
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 294, in get_form_class
    formsets=cls.required_formsets(),
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 240, in required_formsets
    formsets.update(handler_class.required_formsets())
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 240, in required_formsets
    formsets.update(handler_class.required_formsets())
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 603, in required_formsets
    'widgets': child_edit_handler_class.widget_overrides(),
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 216, in widget_overrides
    widgets.update(handler_class.widget_overrides())
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 216, in widget_overrides
    widgets.update(handler_class.widget_overrides())
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 516, in widget_overrides
    content_type=cls.target_content_type(), can_choose_root=cls.can_choose_root)}
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 543, in target_content_type
    cls._target_content_type = [ContentType.objects.get_for_model(target_model)]
  File "/home/alexei/.virtualenvs/test/lib/python3.4/site-packages/django/contrib/contenttypes/models.py", line 80, in get_for_model
    "Error creating new content types. Please make sure contenttypes "
RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.
```

**Comment by ghostwords** [comment]
Thank you for fixing!
