### ISSUE TITLE
Error during system checks since wagtail 1.4.2

### ISSUE THREAD

**Issue by arthru** [torchbox/wagtail#2452]
I just came across a strange error with wagtail 1.4.2 and 1.4.3. Everything is fine with wagtail 1.4.1. I may also say that I work with Django<1.9 (currently 1.8.12)

The stack is the following :

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0f093eaea0>
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/db/models/options.py", line 552, in get_field
    return self.fields_map[field_name]
KeyError: 'body'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 114, in inner_run
    self.validate(display_num_errors=True)
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/core/management/base.py", line 469, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/core/management/base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/wagtailcore/models.py", line 571, in check
    edit_handler = cls.get_edit_handler()
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/utils/decorators.py", line 54, in __call__
    return self.value
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/utils/decorators.py", line 50, in value
    return self.fn(self.cls)
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 743, in get_edit_handler
    return EditHandler.bind_to_model(cls)
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 311, in bind_to_model
    'children': [child.bind_to_model(model) for child in self.children],
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 311, in <listcomp>
    'children': [child.bind_to_model(model) for child in self.children],
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 332, in bind_to_model
    'children': [child.bind_to_model(model) for child in self.children],
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 332, in <listcomp>
    'children': [child.bind_to_model(model) for child in self.children],
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 779, in bind_to_model
    'block_def': model._meta.get_field(self.field_name).stream_block
  File "/home/arthur/.virtualenvs/lepinard/lib/python3.5/site-packages/django/db/models/options.py", line 554, in get_field
    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Page has no field named 'body'
```

I am preparing more infos. Stay tuned !

**Comment by arthru** [comment]
I've published a sample project : https://github.com/arthru/wagtail_issue2452. `./manage.py runserver` triggers the error.

**Comment by arthru** [comment]
This could be related to #2428

**Comment by kaedroho** [comment]
Thanks for reporting

According to the traceback, the error is being raised from ``StreamFieldPanel.bind_to_model``: https://github.com/torchbox/wagtail/blob/09878fcfd87f5b5ea67dd8d178667bce344c02e0/wagtail/wagtailadmin/edit_handlers.py#L779

**Comment by gasman** [comment]
Confirmed that I can reproduce this problem on the sample project. `git bisect` shows that the regression happened in https://github.com/torchbox/wagtail/commit/c823ace6a1c48aab9e93b4387adc30c0fd1d749a

**Comment by gasman** [comment]
OK, worked out what's going on here... the error is at the end of your models.py:

    HomePage.content_panels += [
        StreamFieldPanel('body'),
        PageChooserPanel('contact_page', FormPage),
    ]

At this point `HomePage.content_panels` has not been overridden - it's the same object as `Page.content_panels`, and so this line causes `Page.content_panels` to be extended with the new panels too. So, this is actually a legitimate error, telling you that you've attempted to define `StreamFieldPanel('body')` on `Page`, which is a field that doesn't exist.

c823ace6a1c48aab9e93b4387adc30c0fd1d749a makes this error visible because it adds a system check that tries to construct all edit handlers on startup, but the same error would also have occurred on earlier versions if you'd tried to create a plain instance of `Page`.

**Comment by arthru** [comment]
Ok, my bad...

Sorry for this disturbing issue. And thank you for your nice work !
