### ISSUE TITLE
Using waitress over sockets breaks on SERVER_PORT

### ISSUE THREAD

**Issue by nadersoliman** [torchbox/wagtail#2667]
In a nutshell, I have the following waitress bootstrapping 

```
from waitress import serve
from website import wsgi

# touch app-initialized
open('/tmp/app-initialized', 'w').close()

# start waitress
serve(wsgi.application, unix_socket='/tmp/nginx.socket')
```

and it breaks with the following stack trace

```
Connected to pydev debugger (build 145.972)
serving on http://unix:/tmp/nginx.socket
ERROR    [2016-06-02 13:03:59,982] [none] django.request: Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/handlers/base.py", line 123, in get_response
    response = middleware_method(request)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailcore/middleware.py", line 13, in process_request
    request.site = Site.find_for_request(request)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailcore/models.py", line 150, in find_for_request
    output_field=IntegerField(),
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/query.py", line 908, in annotate
    clone.query.add_annotation(annotation, alias, is_summary=False)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/sql/query.py", line 987, in add_annotation
    summarize=is_summary)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/expressions.py", line 818, in resolve_expression
    c.cases[pos] = case.resolve_expression(query, allow_joins, reuse, summarize, for_save)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/expressions.py", line 752, in resolve_expression
    c.condition = c.condition.resolve_expression(query, allow_joins, reuse, summarize, False)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/query_utils.py", line 92, in resolve_expression
    clause, joins = query._add_q(self, reuse, allow_joins=allow_joins, split_subq=False)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1203, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1099, in build_lookup
    return final_lookup(lhs, rhs)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/lookups.py", line 19, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/lookups.py", line 57, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 1860, in get_prep_lookup
    return super(IntegerField, self).get_prep_lookup(lookup_type, value)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 744, in get_prep_lookup
    return self.get_prep_value(value)
  File "/home/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 1854, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '/tmp/nginx.socket'
```

it turns out that SERVER_PORT contains /tmp/nginx.socket

![image](https://cloud.githubusercontent.com/assets/1029009/15745693/7e0061d2-28d3-11e6-9f50-7214a1c2fe88.png)

![image](https://cloud.githubusercontent.com/assets/1029009/15745742/ba6d8c30-28d3-11e6-85a3-2ab65aa1b30c.png)

I really don't know if this is waitress problem (should provide meaningful value in the SERVER_PORT when running over a socket), or is it a problem in wagtail trying to figure out the site based on the SERVER_PORT

Let me know if you have any questions

thanks

**Comment by syphar** [comment]
keep it simple: don't front it with nginx :)

**Comment by syphar** [comment]
I would be very surprised it waitress is not fast enough

**Comment by nadersoliman** [comment]
Well after investigation, while the problem manifests in wagtail, I feel the responsibility of a fix relies on the fact that using nginx configuration we can override the wsgi SERVER_PORT or for waitress to be a bit smart when it comes to detecting the SERVER_PORT. So far I can't find an adequate solution from nginx configuration and waitress documentation doesn't provide clues on how to override this.
