### ISSUE TITLE
Error when creating a new page

### ISSUE THREAD

**Issue by frague59** [torchbox/wagtail#2917]
Hi, 

I've created a PublicationPage model: 

```python
class Illustrated(models.Model):
    illustration = models.ForeignKey('wagtailimages.Image',
                                     null=True,
                                     blank=True,
                                     on_delete=models.SET_NULL,
                                     related_name='+',
                                     verbose_name=_('Illustration'))

    credit = models.CharField(max_length=255, default=_('All rights reserved'))

    class Meta:
        abstract = True

    # Admin panels
    content_panels = [ImageChooserPanel('illustration'), FieldPanel('credit'), ]

    # Searches
    search_fields = []

class PublicationPage(Illustrated, Page):
    intro = RichTextField(verbose_name=_('Heading'), blank=True)

    body = RichTextField(verbose_name=_('Body'), blank=True)

    class Meta:
        verbose_name = _('Publication page')
        verbose_name_plural = _('Publication pages')
    # Admin panels
    content_panels = Page.content_panels + Illustrated.content_panels + [FieldPanel('intro'),
                                                                         FieldPanel('body', classname='full'), ]
    # Searches
    search_fields = Page.search_fields + Illustrated.search_fields + [index.SearchField('intro'),
                                                                      index.SearchField('body'), ]

    # Parent page type / sub-pages
    parent_page_types = ['publications.PublicationHomePage']
    subpage_types = ['publications.PublicationPage']

    def __str__(self):
        return self.title + ' ( PublicationPage )'
```
The 
When I tries to create an instance for the page, using the admin interface, I have the folowing error : 
```
Traceback (most recent call last):
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 289, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/wagtail/wagtailadmin/decorators.py", line 23, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/wagtail/wagtailadmin/views/pages.py", line 198, in create
    parent_page.add_child(instance=page)
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/treebeard/mp_tree.py", line 970, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/treebeard/mp_tree.py", line 339, in process
    if newobj.pk:
  File "/home/fguerin/Boulot/workspace/django/intranet_wagtail/virtualenv/lib/python2.7/site-packages/django/db/models/base.py", line 536, in _get_pk_val
    return getattr(self, meta.pk.attname)
AttributeError: 'OneToOneField' object has no attribute 'attname'
```
I'm using wagtail 15.6 n a fresh install.

Thanks for your help !

**Comment by kaedroho** [comment]
Which versions of Django and django-treebeard do you have installed?

**Comment by frague59** [comment]
at this time, django 1.9 + treebeard 2.0 + wagtail 1.5, I've moved to wagtail 1.6 + django 1.10, I've no issue animore.

Thanks ! wagtail is realy awesome, I've re-developed my mezzanine stuck (and crashed) within **hours**, when I did spend month to develop the initial version...

**Comment by kaedroho** [comment]
>  treebeard 2.0

Looks like this was most likely the problem. Treebeard 2 was released in 2014 (so probably didn't have Django 1.9 support!)
