### ISSUE TITLE
MySQL: Specified key was too long

### ISSUE THREAD

**Issue by elwinbuisman** [torchbox/wagtail#2953]
Applying wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field...Traceback (most recent call last):

  File "./manage.py", line 17, in <module>

    execute_from_command_line(sys.argv)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line

    utility.execute()

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute

    output = self.handle(*args, **options)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 202, in handle

    targets, plan, fake=fake, fake_initial=fake_initial

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/migrations/executor.py", line 97, in migrate

    state = self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/migrations/executor.py", line 132, in _migrate_all_forwards

    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/migrations/executor.py", line 237, in apply_migration

    state = migration.apply(state, schema_editor)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply

    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards

    schema_editor.create_model(model)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 295, in create_model

    self.execute(sql, params or None)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 112, in execute

    cursor.execute(sql, params)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute

    return super(CursorDebugWrapper, self).execute(sql, params)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute

    return self.cursor.execute(sql, params)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__

    six.reraise(dj_exc_type, dj_exc_value, traceback)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute

    return self.cursor.execute(sql)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute

    return self.cursor.execute(query, args)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute

    self.errorhandler(self, exc, value)

  File "/Users/user/virtualenvs/project/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler

    raise errorclass, errorvalue

django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 1000 bytes')

Due to some limitations in my next project I have to use MySQL. When running the initial migrations, I'm getting the above error. It's somewhat difficult to find out which key it is. Mostly (in previous experiences) it's caused by "unique" or "unique together" indexes.

**Comment by gasman** [comment]
Hi @elwinbuisman - do you have your database set up with utf8mb4 encoding? This sounds like it might be related to #2925.

**Comment by elwinbuisman** [comment]
Hi @gasman Yep, I sure do. That's the only way to get proper utf8 support. This issue is surely related. Difference thought, I've managed to work around the problem he is having by using MyIsam as engine. This allows fields to have 'normal' lengths. But, thus, resulting into index/ key-length problems.

**Comment by bkfox** [comment]
Is there any update about this problem? I exactly have the same problem, and also tried using utf8mb4 encoding. I did a little digging showing the sql queries generated by Django.

 Seems the problem is at least present on two migrations `wagtailimages.0001_initial` and `wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field`.

wagtailimage migration output:
```
QUERY: b'CREATE TABLE `wagtailimages_rendition` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `file` varchar(100) NOT NULL, `width` integer NOT NULL, `height` integer NOT NULL, `focal_point_key` varchar(255) NULL, `filter_id` integer NOT NULL, `image_id` integer NOT NULL)'
# [...] crashes after this request:
QUERY: b'ALTER TABLE `wagtailimages_rendition` ADD CONSTRAINT `wagtailimages_rendition_image_id_03110280_uniq` UNIQUE (`image_id`, `filter_id`, `focal_point_key`)'
```

wagtailcore migration output:

```
# crashes after this request:
QUERY: b'CREATE TABLE `wagtailcore_page` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `path` varchar(255) NOT NULL UNIQUE, `depth` integer UNSIGNED NOT NULL, `numchild` integer UNSIGNED NOT NULL, `title` varchar(255) NOT NULL, `slug` varchar(255) NOT NULL, `live` bool NOT NULL, `has_unpublished_changes` bool NOT NULL, `url_path` longtext NOT NULL, `seo_title` varchar(255) NOT NULL, `show_in_menus` bool NOT NULL, `search_description` longtext NOT NULL, `go_live_at` datetime(6) NULL, `expire_at` datetime(6) NULL, `expired` bool NOT NULL, `content_type_id` integer NOT NULL, `owner_id` integer NULL, `locked` bool NOT NULL, `latest_revision_created_at` datetime(6) NULL, `first_published_at` datetime(6) NULL)'
```

The error raised is always the same: ```_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')```

**Comment by JanMalte** [comment]
This bug still exists. Any news?

**Comment by kevinworthington** [comment]
Looks like @gasman figured this out during #3256.
Following his advice I was able to resolve this issue by calling the following mysql query against my database
`ALTER DATABASE myDbName CHARACTER SET utf8 COLLATE utf8_general_ci;`
then running 
`python manage.py migrate`
from the CLI continued without error

**Comment by frankyhung93** [comment]
Just experienced this with wagtail 2.9.2.

Is there any way to pass the wagtail migrations while using the 'utf8mb4' charset in mysql?
