### ISSUE TITLE
Erro on execute migrate when plug 'wagtail.contrib.modeladmin' in INSTALLED_APPS

### ISSUE THREAD

**Issue by lucassimon** [torchbox/wagtail#2958]
Hello

When I plug modeladmin in installed_apps and run migrate command i got this error

```
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 534, in check
    errors = super(Page, cls).check(**kwargs)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailsearch/index.py", line 99, in check
    errors = super(Indexed, cls).check(**kwargs)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/db/models/base.py", line 1266, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/db/models/base.py", line 1337, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailcore/fields.py", line 130, in check
    errors.extend(self.stream_block.check(field=self, **kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 244, in check
    for name, child_block in self.child_blocks.items():
  File "/usr/lib/python2.7/collections.py", line 115, in items
    return [(key, self[key]) for key in self]

```

**Comment by chrxr** [comment]
Hi @lucassimon, what version of Wagtail are you running?

**Comment by lucassimon** [comment]
Hi,

wagtail 1.6 has no metadata

**Comment by gasman** [comment]
Hi @lucassimon - your traceback seems to be incomplete, as it's missing the actual error message. Please can you post the complete error report?

**Comment by lucassimon** [comment]
Hello @gasman,


I use stream block in content page and in blog.
Maybe something is wrong the way build ContentPage.
If you need more info let me know.


base.py 

```
"""
Django settings for instituto_site project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from __future__ import absolute_import, unicode_literals

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import raven
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'home',
    'search',
    'core',
    'blog',
    'social',
    'quotes',
    'team',

    'wagtail.wagtailforms',
    'wagtail.wagtailredirects',
    'wagtail.wagtailembeds',
    'wagtail.wagtailsites',
    'wagtail.wagtailusers',
    'wagtail.wagtailsnippets',
    'wagtail.wagtaildocs',
    'wagtail.wagtailimages',
    'wagtail.wagtailsearch',
    'wagtail.wagtailadmin',
    'wagtail.wagtailcore',
    'wagtail.contrib.settings',
    "wagtail.contrib.wagtailsitemaps",
    'wagtail.contrib.modeladmin',

    'modelcluster',
    'taggit',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'raven.contrib.django.raven_compat',
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'wagtail.wagtailcore.middleware.SiteMiddleware',
    'wagtail.wagtailredirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'instituto_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wagtail.contrib.settings.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'instituto_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Wagtail settings
TAGGIT_CASE_INSENSITIVE = True

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = 'http://institutom.com.br'


RAVEN_CONFIG = {
    'dsn': 'https://<key>:<secret>@app.getsentry.com/<project>',
}
```

dev.py
```
from __future__ import absolute_import, unicode_literals

from .base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dt-cxglk7lpe6kj2u6(!8zxdch22k*!cq#2q8a!s1l407tlv&+'


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'instituto_site',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': 5432
    }
}

# ######### CACHE CONFIGURATION
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
# ######### END CACHE CONFIGURATION


# ######### INSTALLED APPS CONFIGURATION

INSTALLED_APPS += [
    'debug_toolbar',
    'django_nose',
]

# IPs allowed to see django-debug-toolbar output.
INTERNAL_IPS = ("127.0.0.1",)


MIDDLEWARE_CLASSES += ["debug_toolbar.middleware.DebugToolbarMiddleware", ]


DEBUG_TOOLBAR_CONFIG = {
    # If set to True (default), the debug toolbar will show an intermediate
    # page upon redirect so you can view any debug information prior to
    # redirecting. This page will provide a link to the redirect
    # destination
    # you can follow when ready. If set to False, redirects will proceed as
    # normal.
    'INTERCEPT_REDIRECTS': False,


    # An array of custom signals that might be in your project, defined as
    # the
    # python path to the signal.
    'EXTRA_SIGNALS': [],


    # If set to True (the default) then a template's context will be
    # included
    # with it in the Template debug panel. Turning this off is useful when
    # you
    # have large template contexts, or you have template contexts with lazy
    # datastructures that you don't want to be evaluated.
    'SHOW_TEMPLATE_CONTEXT': True,

}
# ######### END DJANGO-DEBUG-TOOLBAR CONFIGURATION

RAVEN_CONFIG = {
    'dsn': ''
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'sentry': {
            'level': 'INFO',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
        },
        'sqlhandler': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'sqlformatter'
        }
    },
    'formatters': {
        'sqlformatter': {
            '()': 'sqlformatter.SqlFormatter',
            'format': '%(levelname)s %(message)s',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins', 'sqlhandler', 'sentry'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'raven': {
            'level': 'DEBUG',
            'handlers': ['sentry'],
            'propagate': True,
        },
        'sentry.errors': {
            'level': 'DEBUG',
            'handlers': ['sentry'],
            'propagate': True,
        },
        'py.warnings': {
            'handlers': ['console'],
            'propagate': False
        },
    }
}
RAVEN_CONFIG = {}
try:
    from .local import *
except ImportError:
    pass

```

``` 
# -*- coding:utf-8 -*-
from __future__ import unicode_literals
# Stdlib imports

# Core Django imports
from django.db import models
from django.utils.translation import ugettext as _
# Third-party app imports

from wagtail.wagtailsnippets.models import register_snippet
from wagtail.wagtailcore.models import Page
from wagtail.wagtailadmin.edit_handlers import (
    FieldPanel, MultiFieldPanel,
    StreamFieldPanel
)
from wagtail.wagtailcore import blocks
from wagtail.wagtailcore.fields import StreamField
from wagtail.wagtailimages.blocks import ImageChooserBlock
from wagtail.wagtailembeds.blocks import EmbedBlock
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsearch import index
from taggit.models import TaggedItemBase, Tag
from modelcluster.tags import ClusterTaggableManager
from modelcluster.fields import ParentalKey


# Imports from your apps
from .blocks import ImageCarouselBlock, GoogleMapBlock
from quotes.models import Quote
from quotes.blocks import QuoteChooserBlock
from wagtail.contrib.settings.models import BaseSetting, register_setting
# Imports from your apps


@register_setting
class SocialMediaSettings(BaseSetting):
    facebook = models.URLField(
        help_text=_('Sua página no facebook'),
        blank=True,
        null=True
    )

    twitter = models.CharField(
        max_length=255,
        help_text=_('Seu usuário no twitter, sem o @'),
        blank=True,
        null=True
    )

    instagram = models.CharField(
        max_length=255,
        help_text=_('Seu usuário no Instagram, sem o @'),
        blank=True,
        null=True
    )

    api_instagram_enabled = models.BooleanField(
        default=False,
        help_text=_('Habilita a utilizacao da api do instagram'),
    )

    api_instagram_user_id = models.CharField(
        max_length=255,
        help_text=_('Usuário de acesso a api do instagram'),
        blank=True,
        null=True
    )

    api_instagram_key = models.CharField(
        max_length=255,
        help_text=_('Chave de acesso a api do instagram'),
        blank=True,
        null=True
    )

    api_instagram_secret = models.CharField(
        max_length=255,
        help_text=_('Chave secreta de acesso a api do instagram'),
        blank=True,
        null=True
    )

    youtube = models.URLField(
        help_text=_('Seu canal no youtube ou o endereço do seu usuario'),
        blank=True,
        null=True
    )

    google = models.URLField(
        help_text=_('O endereço do google plus'),
        blank=True,
        null=True
    )

    linkedin = models.URLField(
        help_text=_('O endereço do perfil no linkedin'),
        blank=True,
        null=True
    )


@register_setting
class CompanySettings(BaseSetting):
    name = models.CharField(
        max_length=255,
        help_text=_('Nome da empresa'),
    )

    abstract = models.CharField(
        max_length=255,
        help_text=_('Breve resumo da empresa'),
    )

    address = models.CharField(
        max_length=255,
        help_text=_('Endereço completo, sem o bairro e o complemento'),
        blank=True,
        null=True
    )

    complement = models.CharField(
        max_length=255,
        help_text=_('Informações adicionais do endereço'),
        blank=True,
        null=True
    )

    zipcode = models.CharField(
        max_length=255,
        help_text=_('CEP'),
        blank=True,
        null=True
    )

    city = models.CharField(
        max_length=255,
        help_text=_('Cidade/Estado/Pais'),
        blank=True,
        null=True
    )

    email = models.EmailField(
        max_length=255,
        help_text=_('Email oficial para contato'),
    )

    phone = models.CharField(
        max_length=255,
        help_text=_('Telefone  para contato'),
    )


@register_setting
class ZohoSettings(BaseSetting):

    api_campaign_enabled = models.BooleanField(
        default=False,
        help_text=_('Habilita a utilizacao da api do zoho'),
    )

    api_campaign_token = models.CharField(
        max_length=255,
        help_text=_('Token de acesso'),
        blank=True,
        null=True
    )

    api_campaign_list_subscribe_key = models.CharField(
        max_length=255,
        help_text=_(
            'Chave de acesso para inscrever contatos em uma lista de campanhas'
        ),
        blank=True,
        null=True
    )


class ContentPageTag(TaggedItemBase):
    content_object = ParentalKey('ContentPage', related_name='tagged_items')


@register_snippet
class ContentTag(Tag):
    class Meta:
        proxy = True


class ContentPage(Page):

    header_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
        verbose_name=_('Header image')
    )

    intro = models.CharField(max_length=512, blank=True, null=True)

    body = StreamField(
        [
            (_(u'heading'), blocks.CharBlock(classname="full title")),
            (_(u'paragraph'), blocks.RichTextBlock()),
            (_(u'image'), ImageChooserBlock(icon="image")),
            (_(u'google_map'), GoogleMapBlock()),
            (
                'embedded_video',
                EmbedBlock(
                    icon="media",
                    classname="full title"
                )
            ),
            (
                'image_carousel',
                blocks.ListBlock(
                    ImageCarouselBlock(),
                    template='core/blocks/carousel.html',
                    icon="image"
                )
            ),
            (
                'Quote',
                QuoteChooserBlock(
                    Quote,
                    icon='openquote'
                )
            ),
        ],
        null=True,
        blank=True
    )

    tags = ClusterTaggableManager(through=ContentPageTag, blank=True)

    search_fields = Page.search_fields + [
        index.SearchField('body'),
        index.SearchField('intro'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('intro', classname="full"),
        MultiFieldPanel([
            FieldPanel('tags'),
        ], heading="Tags"),
        ImageChooserPanel('header_image'),
        StreamFieldPanel('body'),
    ]

```

Traceback
```
# lucas @ notebook-vostro in ~/workspace-python/websites/mysite/instituto_site on git:master x [16:10:11] 
$ python manage.py migrate  --settings=instituto_site.settings.dev
/home/lucas/venvs/mysite/src/wagtail-blog/blog/models.py:261: RemovedInWagtail17Warning: Using a tuple for search_fields on Page subclasses is deprecated, use a list instead
  index.SearchField('body'),
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 537, in check
    errors = super(Page, cls).check(**kwargs)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailsearch/index.py", line 99, in check
    errors = super(Indexed, cls).check(**kwargs)
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/db/models/base.py", line 1266, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/django/db/models/base.py", line 1337, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailcore/fields.py", line 130, in check
    errors.extend(self.stream_block.check(field=self, **kwargs))
  File "/home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 244, in check
    for name, child_block in self.child_blocks.items():
  File "/usr/lib/python2.7/collections.py", line 115, in items
    return [(key, self[key]) for key in self]
KeyError: <django.utils.functional.__proxy__ object at 0x7f04083a4cd0>
```

debugger in ipdb
```
# lucas @ notebook-vostro in ~/workspace-python/websites/mysite/instituto_site on git:master x [16:23:37] 
$ python manage.py migrate  --settings=instituto_site.settings.dev           
/home/lucas/venvs/mysite/src/wagtail-blog/blog/models.py:261: RemovedInWagtail17Warning: Using a tuple for search_fields on Page subclasses is deprecated, use a list instead
  index.SearchField('body'),
> /home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailcore/blocks/stream_block.py(245)check()
    243         errors = super(BaseStreamBlock, self).check(**kwargs)
    244         import ipdb; ipdb.set_trace()
--> 245         for name, child_block in self.child_blocks.items():
    246 
    247             errors.extend(child_block.check(**kwargs))

ipdb> self.child_blocks.items()
[(u'heading', <wagtail.wagtailcore.blocks.field_block.CharBlock object at 0x7f635f446090>), (u'paragraph', <wagtail.wagtailcore.blocks.field_block.RichTextBlock object at 0x7f635f446190>), (u'imagem', <wagtail.wagtailimages.blocks.ImageChooserBlock object at 0x7f635f446250>), (u'google_map', <core.blocks.GoogleMapBlock object at 0x7f635f4462d0>), (u'embedded_video', <wagtail.wagtailembeds.blocks.EmbedBlock object at 0x7f635f446410>), (u'image_carousel', <wagtail.wagtailcore.blocks.list_block.ListBlock object at 0x7f635f446590>), (u'Quote', <quotes.blocks.QuoteChooserBlock object at 0x7f635f446650>)]
ipdb> c
> /home/lucas/venvs/mysite/local/lib/python2.7/site-packages/wagtail/wagtailcore/blocks/stream_block.py(245)check()
    243         errors = super(BaseStreamBlock, self).check(**kwargs)
    244         import ipdb; ipdb.set_trace()
--> 245         for name, child_block in self.child_blocks.items():
    246 
    247             errors.extend(child_block.check(**kwargs))

ipdb> self.child_blocks.items()
*** KeyError: <django.utils.functional.__proxy__ object at 0x7f635f3a5c10>
ipdb> self.child_blocks
*** KeyError: <django.utils.functional.__proxy__ object at 0x7f635f3a5c10>
```

**Comment by gasman** [comment]
Hi @lucassimon - the problem is here:
```
            (_(u'heading'), blocks.CharBlock(classname="full title")),
            (_(u'paragraph'), blocks.RichTextBlock()),
            (_(u'image'), ImageChooserBlock(icon="image")),
            (_(u'google_map'), GoogleMapBlock()),```

Block names should not be marked as translatable strings, as they are used as internal identifiers. (You can specify a human-readable label for the block by setting a `label` attribute on the block.)
