### ISSUE TITLE
Cannot use HttpResponseRedirect in a Page model get_context

### ISSUE THREAD

**Issue by Benoss** [torchbox/wagtail#3013]
### Issue Summary

Impossible to return HttpResponseRedirectBase from the a Page model in get_context

Traceback:

```
Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\template\response.py", line 109, in render
    self.content = self.rendered_content
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\template\response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\template\context.py", line 267, in make_context
    context.push(original_context)
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\template\context.py", line 59, in push
    return ContextDict(self, *dicts, **kwargs)
  File "C:\Users\Benoit\PycharmProjects\prismatic-website\venv\lib\site-packages\django\template\context.py", line 18, in __init__
    super(ContextDict, self).__init__(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 0; 2 is required
```

### Steps to Reproduce

Create a redirection on any Page model

```
    def get_context(self, request, *args, **kwargs):
        context = super(BlogIndex, self).get_context(request, *args, **kwargs)

        return HttpResponsePermanentRedirect('/')
```

This can be fixed by changing the serve method in wagrailcore.models with a check if the context is a HttpResponseRedirect and return it instead of a template that cannot be rendered

```
    def serve(self, request, *args, **kwargs):
        request.is_preview = getattr(request, 'is_preview', False)

        context = self.get_context(request, *args, **kwargs)
        **if isinstance(context, HttpResponseRedirectBase):
            return context**

        return TemplateResponse(
            request,
            self.get_template(request, *args, **kwargs),
            context
        )
```

### Technical details

* Python version: 2.7.11
* Django version: 1.10.1
* Wagtail version: 1.6.2

**Comment by gasman** [comment]
Hi @Benoss,
This is the intended behaviour. The return value from `get_context` should be a dict of variables to be made available in the template context; returning anything else (such as an HTTP response object) is invalid. If you want a Page model to perform a redirect, you should override its `serve` method instead.
