### ISSUE TITLE
Management command set_url_paths broken in Django 1.10

### ISSUE THREAD

**Issue by benjaoming** [torchbox/wagtail#3092]
### Issue Summary

`python manage.py set_url_paths` (I don't know what the command is for?) is broken in Django 1.10.

Should the command be removed or fixed?

### Steps to Reproduce

1. `python manage.py help set_url_paths`

### Technical details

* Python version: 3.4
* Django version: 1.10.1
* Wagtail version: 1.6.3

```
$ python manage.py help set_url_paths
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File ".virtualenvs/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File ".virtualenvs/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute
    self.fetch_command(options.args[0]).print_help(self.prog_name, options.args[0])
  File ".virtualenvs/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File ".virtualenvs/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File ".virtualenvs/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File ".virtualenvs/venv/lib/python3.4/site-packages/wagtail/wagtailcore/management/commands/set_url_paths.py", line 3, in <module>
    from django.core.management.base import NoArgsCommand
ImportError: cannot import name 'NoArgsCommand'
```

**Comment by gasman** [comment]
Fixed in #3101
