### ISSUE TITLE
Add documents with the same filename created issue after deletion of one

### ISSUE THREAD

**Issue by FlipperPA** [torchbox/wagtail#3108]
### Issue Summary

We have a content editor who accidentally added the same document twice to the Document Library, and then deleted one. After deleting the one, the file was removed. This led to the following error when the remaining document was attempted to be edited: 

`An error occurred (404) when calling the HeadObject operation: Not Found`

### Steps to Reproduce

1. Visit '/[admin]/documents/multiple/add/'
2. Upload a document and change the title to Doc 1
3. Upload the same document and change the title to Doc 2
4. Delete Doc 2
5. Edit Doc 1

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Several options:

1. When deleting, make sure the file name is not associated with any other Document; if it is, delete the row in the database, and not the file itself.
2. Ensure that file names of uploads are unique.

### Technical details

* Python version: 3.5.2
* Django version: 1.10.2
* Wagtail version: 1.6.3
* Browser version: Chrome 53

We are using django-storages and boto3 to store our assets on Amazon S3.

**Comment by gasman** [comment]
Hi @FlipperPA,
I think we've seen this before with images (#1686) - it's a bug in django-storages, since the `get_available_name` function is supposed to ensure that the filename is unique, but doesn't (in the default configuration). Could you see if setting `AWS_S3_FILE_OVERWRITE = False` fixes this?

**Comment by FlipperPA** [comment]
The setting did the trick for documents as well; it added a random 8-char string to the end of the second upload to make it unique. Thanks very much!

**Comment by FlipperPA** [comment]
Just to follow up, I'd recommend only doing this for your media files, not static file. Here's an example `custom_storages.py` I use:

```
from django.conf import settings
from storages.backends.s3boto3 import S3Boto3Storage


class StaticStorage(S3Boto3Storage):
    location = settings.STATICFILES_LOCATION


class MediaStorage(S3Boto3Storage):
    location = settings.MEDIAFILES_LOCATION
    file_overwrite = False
```

**Comment by benpetty** [comment]
Thanks, I had the same problem, and these solutions fixed it going forward.

But, I can't use wagtail to delete the previously uploaded error-ing photos. Clicking the image from the chooser sends me to that images `wagtailimages:edit` route -- which returns a 500 response.

What is the suggested way of removing MEDIA files from wagtail if I cannot access the files edit page?

**Comment by gasman** [comment]
Hi @benpetty - what's the exact error, and what version of Wagtail are you running? As far as I'm aware, the image edit page should have been handling missing files gracefully ever since Wagtail 1.0...

**Comment by benpetty** [comment]
Hi @gasman - thanks for the quick response. I'm running wagtail==1.13, django==1.11.6, boto3==1.4.7, botocore==1.7.30.

From the cms `/images/` chooser, JS console prints a pair of 403s for each item with duplicate file names (ending in `.max-165x165.png`). Yet the thumbnails are visible. Following link to edit page returns 500:

```
botocore.exceptions:ClientError
/wagtail.wagtailimages.views.images:edit

Stack trace
botocore.exceptions:ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
Traceback (most recent call last):
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/api/web_transaction.py", line 1198, in _nr_wsgi_application_wrapper_
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 527, in wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailadmin/urls/__init__.py", line 96, in wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 31, in decorated_view
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailadmin/utils.py", line 140, in wrapped_view_func
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailimages/views/images.py", line 147, in edit
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailimages/models.py", line 105, in get_file_size
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/db/models/fields/files.py", line 77, in size
File "/var/www/tomorrow/env/lib/python3.5/site-packages/storages/backends/s3boto3.py", line 511, in size
File "/var/www/tomorrow/env/lib/python3.5/site-packages/boto3/resources/factory.py", line 339, in property_loader
File "/var/www/tomorrow/env/lib/python3.5/site-packages/boto3/resources/factory.py", line 505, in do_action
File "/var/www/tomorrow/env/lib/python3.5/site-packages/boto3/resources/action.py", line 83, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/botocore/client.py", line 312, in _api_call
File "/var/www/tomorrow/env/lib/python3.5/site-packages/botocore/client.py", line 605, in _make_api_call
```

When trying to add a broken image to a page, JS console prints 403 not founds from cloudfrount, and 500s from `/cms/images/chooser/129/select_format/`.

```
wagtail.wagtailimages.models:SourceImageIOError
/wagtail.wagtailimages.views.chooser:chooser_select_format

Stack trace
wagtail.wagtailimages.models:SourceImageIOError: File does not exist: media/original_images/foo.png
Traceback (most recent call last):
File "/var/www/tomorrow/env/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 30, in accept
File "/var/www/tomorrow/env/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
File "/var/www/tomorrow/env/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/api/web_transaction.py", line 1309, in _nr_wsgi_application_wrapper_
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/api/web_transaction.py", line 837, in __init__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/api/web_transaction.py", line 1198, in _nr_wsgi_application_wrapper_
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 1182, in _wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
File "/var/www/tomorrow/env/lib/python3.5/site-packages/newrelic/hooks/framework_django.py", line 527, in wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailadmin/urls/__init__.py", line 96, in wrapper
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 31, in decorated_view
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailimages/views/chooser.py", line 169, in chooser_select_format
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailimages/models.py", line 271, in get_rendition
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailimages/models.py", line 367, in run
File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
File "/var/www/tomorrow/env/lib/python3.5/site-packages/wagtail/wagtailimages/models.py", line 173, in get_willow_image
```
