### ISSUE TITLE
Custom user model throw AppRegistryNotReady exception

### ISSUE THREAD

**Issue by fakegit** [torchbox/wagtail#3166]
Env:
Python 3.5
Wagtail 1.7
Win7

Code:
```
from wagtail.wagtailusers.forms import UserEditForm
class ProfileEditForm(UserEditForm):
    pass
```

Traceback (most recent call last):
```
  File "d:\Miniconda3\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "d:\Miniconda3\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "d:\Miniconda3\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "d:\Miniconda3\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "d:\Miniconda3\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "d:\Miniconda3\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "d:\Miniconda3\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "d:\Miniconda3\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "d:\Miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\Python\wagtail\nutcms\movie\models.py", line 32, in <module>
    from user import views as user_views
  File "D:\Python\wagtail\nutcms\user\views.py", line 17, in <module>
    from user.forms import ProfileEditForm
  File "D:\Python\wagtail\nutcms\user\forms.py", line 38, in <module>
    from wagtail.wagtailusers.forms import UserEditForm
  File "d:\Miniconda3\lib\site-packages\wagtail\wagtailusers\forms.py", line 20, in <module>
    User = get_user_model()
  File "d:\Miniconda3\lib\site-packages\django\contrib\auth\__init__.py", line 163, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "d:\Miniconda3\lib\site-packages\django\apps\registry.py", line 192, in get_model
    self.check_models_ready()
  File "d:\Miniconda3\lib\site-packages\django\apps\registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by kaedroho** [comment]
Please use the [support group](https://groups.google.com/forum/#!forum/wagtail) for support.

But to answer your question, I think your problem lies here:

> File "D:\Python\wagtail\nutcms\movie\models.py", line 32, in <module>
>    from user import views as user_views
