### ISSUE TITLE
Can not have a field named the same as a Page model

### ISSUE THREAD

**Issue by timheap** [torchbox/wagtail#503]
The following model definition will cause an error when instansiating a Foo:

```python
from django.db import models
from wagtail.wagtailcore.models import Page


class Foo(Page):
    bar = models.CharField(max_length=255)


class Bar(Page):
    pass
```

```python
$ ./manage.py shell
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from wagtailtests.website.models import Foo, Bar
>>> Bar()
<Bar: >
>>> Foo()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/vagrant/wagtail/wagtailcore/models.py", line 305, in __init__
    super(Page, self).__init__(*args, **kwargs)
  File "/home/vagrant/wagtailtests_venv/local/lib/python2.7/site-packages/modelcluster/models.py", line 114, in __init__
    super(ClusterableModel, self).__init__(*args, **kwargs)
  File "/home/vagrant/wagtailtests_venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 407, in __init__
    setattr(self, field.attname, val)
  File "/home/vagrant/wagtailtests_venv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 223, in __set__
    self.related.get_accessor_name(), self.related.opts.object_name))
ValueError: Cannot assign "u''": "Foo.bar" must be a "Bar" instance.
```

This does not happen when using `django.db.models.Model` as the base class of Foo and Bar, so this is a Wagtail issue. I encountered this issue when attempting to create a Page model named `Website`, and had another Page model with a field `website`.

**Comment by kaedroho** [comment]
I've found another issue recently that is related to this.

It is not possible to have two page classes with the same name, even if they're in different apps. This is because the reverse accessor from the Page class would be given the same name causing a clash.

This is possible to work around using the code above to override ``page_ptr``. It is not possible to work around it if your page type decends from an abstract class (form pages for example). The only thing you can do is rename your models.
