### ISSUE TITLE
Django 1.7 migrations do not cleanly apply when upgrading from South

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#671]
According to https://docs.djangoproject.com/en/dev/topics/migrations/#upgrading-from-south , it should be possible to switch out South and run the Django 1.7 migrations on an existing database so that it marks them as applied without running them.

This fails when testing on wagtaildemo (bringing up a 1.6 install, then merging https://github.com/torchbox/wagtaildemo/pull/41 into it) as follows:

    git clone git@github.com:torchbox/wagtaildemo.git
    vagrant up
    git checkout -b kaedroho-django17 master
    git pull https://github.com/kaedroho/wagtaildemo.git django17
    vagrant ssh
    ./manage.py migrate

Output:

    Running migrations:
      Applying contenttypes.0001_initial... FAKED
      Applying auth.0001_initial... FAKED
      Applying admin.0001_initial... FAKED
      Applying taggit.0001_initial... FAKED
      Applying wagtailimages.0001_initial... FAKED
      Applying wagtailcore.0001_initial... FAKED
      Applying wagtailcore.0002_initial_data...Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 160, in handle
        executor.migrate(targets, plan, fake=options.get("fake", False))
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 63, in migrate
        self.apply_migration(migration, fake=fake)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 97, in apply_migration
        migration.apply(project_state, schema_editor)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 107, in apply
        operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
        self.code(from_state.render(), schema_editor)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/wagtail/wagtailcore/migrations/0002_initial_data.py", line 29, in initial_data
        url_path='/',
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/query.py", line 372, in create
        obj.save(force_insert=True, using=self.db)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/base.py", line 590, in save
        force_update=force_update, update_fields=update_fields)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/base.py", line 618, in save_base
        updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/base.py", line 699, in _save_table
        result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/base.py", line 732, in _do_insert
        using=using, raw=raw)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
        return query.get_compiler(using=using).execute_sql(return_id)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
        cursor.execute(sql, params)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.IntegrityError: duplicate key value violates unique constraint "wagtailcore_page_path_key"
    DETAIL:  Key (path)=(0001) already exists.

**Comment by gasman** [comment]
Closing as unnecessary. Having to run `./manage.py migrate --force` as a one-off on all instances of a site is clearly not a deal-breaker.
