### ISSUE TITLE
New Relic Python Agent breaks RoutablePageMixin

### ISSUE THREAD

**Issue by akrawchyk** [torchbox/wagtail#764]
When the New Relic Python Agent is configured with wsgi, any pages served with the `RoutablePageMixin` returns a 500 error related to `getattr()` on line 44 of `wagtailroutablepage/models.py`:

```
Internal Server Error: /about/press/
Traceback (most recent call last):
  File "/home/www/SCRUBBED/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/www/SCRUBBED/venv/local/lib/python2.7/site-packages/newrelic-2.34.0.29/newrelic/hooks/framework_django.py", line 497, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/www/SCRUBBED/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/views.py", line 20, in serve
    page, args, kwargs = request.site.root_page.specific.route(request, path_components)
  File "/home/www/SCRUBBED/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 397, in route
    return subpage.specific.route(request, remaining_components)
  File "/home/www/SCRUBBED/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 397, in route
    return subpage.specific.route(request, remaining_components)
  File "/home/www/SCRUBBED/venv/local/lib/python2.7/site-packages/wagtail/contrib/wagtailroutablepage/models.py", line 58, in route
    view, args, kwargs = self.resolve_subpage(path)
  File "/home/www/SCRUBBED/venv/local/lib/python2.7/site-packages/wagtail/contrib/wagtailroutablepage/models.py", line 44, in resolve_subpage
    view = getattr(self, view)
TypeError: getattr(): attribute name must be string
```

My Page is setup like so:

```
class PressIndexPage(Page, RoutablePageMixin):
    subpage_urls = (
        url(r'^$', 'press_index_page', name='press_index_page'),
        url(r'^in_the_news/$', 'press_news_index_page', name='press_news_index_page'),
        url(r'^press_releases/$', 'press_releases_index_page', name='press_releases_index_page'),
    )

    def press_index_page(self, request):
        """
        View function for returning 2 news and 2 press releases
        """
        context = super(PressIndexPage, self).get_context(request)
        context['pages'] = {
            "press_releases": self.press_releases[:2],
            "news": self.news[:2]
        }
        return render(request, 'press/press_index_page.html', context)

    def press_news_index_page(self, request, page=None):
        """
        View function for returning all news
        """
        context = self.get_context(request, 'news')
        return render(request, 'press/press_news_index_page.html', context)

    def press_releases_index_page(self, request, page=None):
        """
        View function for returning all press releases
        """
        context = self.get_context(request, 'press_releases')
        return render(request, 'press/press_releases_index_page.html', context)

    @property
    def news(self):
        news = PressPage.objects.live().descendant_of(self).filter(is_news=True)
        news = news.order_by('-pub_date')
        return news

    @property
    def press_releases(self):
        press_releases = PressPage.objects.live().descendant_of(self).filter(is_press_release=True)
        press_releases = press_releases.order_by('-pub_date')
        return press_releases

    def get_context(self, request, tipe):
        if (tipe == 'news'):
            pages = self.news

        if (tipe == 'press_releases'):
            pages = self.press_releases

        page = request.GET.get('page')
        paginator = Paginator(pages, 10)  # TODO make this num editable

        try:
            pages = paginator.page(page)
        except PageNotAnInteger:
            pages = paginator.page(1)
        except EmptyPage:
            pages = paginator.page(paginator.num_pages)

        context = super(PressIndexPage, self).get_context(request)
        context['pages'] = pages

        return context
```

**Comment by kerin** [comment]
We've just run into this issue today - was this closed because it's fixed in 0.9?

**Comment by akrawchyk** [comment]
It was closed because I thought it had been fixed by 0.8. I forgot to reopen it, doing so now. Thanks!

**Comment by kaedroho** [comment]
This might be fixed by: https://github.com/torchbox/wagtail/pull/1161 as this doesn't require using the ``url`` function in a non-standard way.

**Comment by kaedroho** [comment]
Could you check this with the new ``RoutablePage`` syntax introduced in 1.0? I think this would be fixed now

**Comment by akrawchyk** [comment]
@kaedroho we've patched our app and it is currently in use in production at https://www.fosi.org/about/press/. Seems to be working well so far :+1:
