### ISSUE TITLE
Update to treebeard 3.0

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#930]
This fixes many of the Django 1.7 warnings we get.

It also drops support for both Python 3.2 and 3.3 so we might need to tread carefully if we decide to adopt it. We already have a dependency that doesn't support 3.2 (``libsass``) which doesn't seem to be causing any problems for the time being (tests all pass, but I've not cheked it recently).

**Comment by SkiftCreative** [comment]
pre treebeard 3.0 also does not have this fix:

http://code.tabo.pe/django-treebeard/issue/74/trouble-installing-with-python3-and-docker

which means it cannot be easily cloned into docker. I know the issue is closed, but wanted to add this comment for others searching for this issue. My error was:

```
Downloading/unpacking django-treebeard==2.0 (from wagtail==0.8.5->-r /opt/django/app/requirements.txt (line 9))
  Running setup.py (path:/tmp/pip-build-llk69xlv/django-treebeard/setup.py) egg_info for package django-treebeard
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-llk69xlv/django-treebeard/setup.py", line 38, in <module>
        long_description=open(root_dir() + '/README.rst').read(),
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 170: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-llk69xlv/django-treebeard/setup.py", line 38, in <module>

    long_description=open(root_dir() + '/README.rst').read(),

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 170: ordinal not in range(128)
```

**Comment by SalahAdDin** [comment]
i haven't problem with django-treebeard 3.0 in my projects and web server.
